#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_PGUP, KC_HOME, KC_NLCK, KC_P9, KC_P8, KC_P7, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PGDN, KC_END, KC_DEL, KC_P6, KC_P5, KC_P4, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_DOT, KC_UP, KC_COMM, LGUI_T(KC_P3), LALT_T(KC_P2), LCTL_T(KC_P1), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RGHT, KC_DOWN, KC_LEFT, LSFT_T(KC_PDOT), LT(1,KC_P0), LT(1,KC_P0), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
	[1] = LAYOUT(KC_PSLS, KC_PMNS, RESET, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_PAST, KC_PPLS, KC_BSPC, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_RPRN, KC_TRNS, KC_LPRN, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_SPC, KC_TRNS, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO)
};
